name: in_sync_interface
description: An interface for synchronization functional. Used by in_sync.
version: 1.5.0+1
homepage: https://github.com/innim/
repository: https://github.com/Innim/in_sync_interface
issue_tracker: https://github.com/Innim/in_sync_interface/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies: 
  innim_lint: ^0.5.0+1
  test: ^1.20.1
