name: in_sync_interface
description: An interface for synchronization functional. Used by in_sync.
version: 0.1.2
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_remote_error
issue_tracker: https://github.com/Innim/flutter_remote_error/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:

flutter:
